export const AUCTION_CATEGORY_OPTIONS = [
  'Electronics',
  'Smartphones & Tablets',
  'Computers & Accessories',
  'Gaming',
  'Fashion',
  'Sneakers',
  'Luxury Watches',
  'Jewelry',
  'Art & Collectibles',
  'Automotive',
  'Home & Decor',
  'Industrial Equipment',
  'Other',
];
